angular.module('app')
    .config(function($stateProvider,$urlRouterProvider){
        $urlRouterProvider.otherwise('/home');
        $stateProvider
            .state('home',{
                url:'/home',
                templateUrl:'home/home.html',
                controller:"homeCtrl"
            })
            .state('profile',{
                url:'/profile',
                templateUrl:'tabs/profile.html',
                controller:'profileCtrl'
            })
            .state('home.aboutTab',{
                url:'/aboutTab',
                templateUrl:'tabs/aboutTab.html'
            })
            .state('home.friends',{
                url:'/friends',
                templateUrl:'tabs/friends.html'
            })
            .state('contact',{
                url:'/contact',
                templateUrl:'tabs/contact.html',
                controller:'blogCtrl'
            })
            .state('home.photos',{
                url:'/photos',
                templateUrl:'tabs/photos.html'
            })
            .state('about',{
                url:'/about',
                templateUrl:'about/about.html',
                controller:"aboutCtrl"
            });
    });
